"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, type CurrentUser } from "../utils/api";
type AuthMode = "signIn" | "signUp";
export function AuthPanel() {
  const [mode, setMode] = useState<AuthMode>("signIn"); const [user, setUser] = useState<CurrentUser | null>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [canResend, setCanResend] = useState(false);
  useEffect(() => { void api<{ user: CurrentUser }>("/auth/me").then(data => setUser(data.user)).catch(() => setUser(null)).finally(() => setLoading(false)); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setError(null); setMessage(null); setCanResend(false); try { if (mode === "signUp") { const result = await api<{ message: string }>("/auth/register", { method: "POST", body: JSON.stringify({ email, password }) }); setMessage(result.message); setPassword(""); } else { const result = await api<{ user: CurrentUser }>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); setUser(result.user); setPassword(""); setMessage("Signed in successfully."); } } catch (reason) { const text = reason instanceof Error ? reason.message : "Request failed."; setError(text); setCanResend(mode === "signIn" && text.startsWith("Confirm your email")); } finally { setSubmitting(false); } }
  async function logout() { setSubmitting(true); try { await api("/auth/logout", { method: "POST" }); setUser(null); setMessage("Signed out successfully."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not sign out."); } finally { setSubmitting(false); } }
  async function resendVerification() { setSubmitting(true); setError(null); setMessage(null); try { const result = await api<{ message: string }>("/auth/resend-verification", { method: "POST", body: JSON.stringify({ email }) }); setMessage(result.message); setCanResend(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not resend verification email."); } finally { setSubmitting(false); } }
  if (loading) return <p className="auth-status" role="status">Checking your session…</p>;
  if (user) return <section id="account" className="auth-panel"><p className="eyebrow">ACCOUNT</p><h2>You&apos;re signed in</h2><p className="auth-copy">{user.email}</p><p className="auth-copy">Your seat is ready at the Hold&apos;em practice table.</p><a className="primary auth-link" href="/table">Go to table</a><button className="secondary auth-button" type="button" onClick={logout} disabled={submitting}>{submitting ? "Signing out…" : "Sign out"}</button>{message && <p className="auth-status">{message}</p>}{error && <p className="auth-error">{error}</p>}</section>;
  const signUp = mode === "signUp";
  return <section id="account" className="auth-panel"><p className="eyebrow">PLAYER ACCOUNT</p><h2>{signUp ? "Create your account" : "Welcome back"}</h2><p className="auth-copy">{signUp ? "Confirm your email before you can take a seat." : "Sign in to access the poker table."}</p><form onSubmit={submit} className="auth-form"><label>Email<input type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} required disabled={submitting} /></label><label>Password<input type="password" autoComplete={signUp ? "new-password" : "current-password"} value={password} onChange={event => setPassword(event.target.value)} minLength={8} required disabled={submitting} /></label><button className="primary auth-button" type="submit" disabled={submitting}>{submitting ? "Please wait…" : signUp ? "Create account" : "Sign in"}</button></form><button className="auth-switch" type="button" onClick={() => { setMode(signUp ? "signIn" : "signUp"); setError(null); setMessage(null); setCanResend(false); }} disabled={submitting}>{signUp ? "Already confirmed? Sign in" : "New here? Create an account"}</button>{canResend && <button className="auth-switch resend-button" type="button" onClick={resendVerification} disabled={submitting}>Resend verification email</button>}{message && <p className="auth-status">{message}</p>}{error && <p className="auth-error" role="alert">{error}</p>}</section>;
}
